{
 "title": "Dash-1",
 "time": { "from": "2023-01-02T05:09:29.835Z", "to": "2023-01-02T05:11:54.478Z" },
 "panels": [
  {
   "title": "AVG Population Growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "sql6587654",
     "rawSql": "SELECT AVG(popgrowth) \r\nFROM sql6587654.realtimesummary \r\nGROUP BY ts \r\norder by ts desc"
    }
   ]
  },
  {
   "title": "Time series (Population Growth)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 0 },
   "targets": [
    {
     "dataset": "sql6587654",
     "rawSql": "SELECT SUM(popgrowth) as Population , ts FROM sql6587654.realtimesummary \r\nwhere popgrowth > 0\r\nGROUP BY ts order by ts desc LIMIT 50 "
    }
   ]
  },
  {
   "title": "Time series (CO2)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 13, "y": 0 },
   "targets": [
    {
     "dataset": "sql6587654",
     "rawSql": "SELECT SUM(CO2) as CO2 , ts FROM sql6587654.realtimesummary \r\nwhere co2 > 0\r\nGROUP BY ts ORDER BY ts DESC LIMIT 50 "
    }
   ]
  },
  {
   "title": "AVG CO2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sql6587654",
     "rawSql": "SELECT AVG(co2) FROM sql6587654.realtimesummary \r\nwhere co2 > 0\r\nGROUP BY ts\r\norder BY ts desc"
    }
   ]
  },
  {
   "title": "Correlation : Population growth and CO2",
   "type": "xychart",
   "description": " ",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 7 },
   "targets": [
    {
     "dataset": "sql6587654",
     "rawSql": "SELECT popgrowth, co2 \r\nFROM sql6587654.realtimesummary \r\norder by ts desc \r\nLIMIT 50"
    }
   ]
  },
  {
   "title": "CO2 vs Predict CO2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 13, "y": 7 },
   "targets": [
    {
     "dataset": "sql6587654",
     "rawSql": "SELECT co2, ts FROM sql6587654.realtimesummary where co2 > 0 group BY ts DESC LIMIT 50 "
    },
    {
     "dataset": "sql6587654",
     "rawSql": "SELECT pred_co2, ts FROM sql6587654.realtimesummary where pred_co2 > 0 group BY ts DESC LIMIT 50 "
    }
   ]
  },
  {
   "title": "AVG Predict CO2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sql6587654",
     "rawSql": "SELECT AVG(pred_co2) \r\nFROM sql6587654.realtimesummary \r\nwhere pred_co2 > 0\r\nGROUP BY ts \r\nORDER BY ts DESC "
    }
   ]
  },
  {
   "title": "Population Growth",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sql6587654",
     "rawSql": "SELECT sum(popgrowth) FROM sql6587654.realtimesummary ORDER BY ts DESC "
    }
   ]
  },
  {
   "title": "Energy",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 7, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sql6587654",
     "rawSql": "SELECT energy FROM sql6587654.realtimesummary \r\nOrder BY ts desc"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sql6587654",
     "rawSql": "SELECT CO2 FROM sql6587654.realtimesummary \r\nOrder BY ts desc"
    }
   ]
  }
 ]
}